format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$c\
$golang\
$helm\
$lua\
$pulumi\
$python\
$rust\
$terraform\
$zig\
$nix_shell\
$kubernetes\
$cmd_duration\
$line_break\
$jobs\
$status\
$shell\
$character
"""
#right_format = "$kubernetes"
palette = "tokyo_night"
add_newline = true
command_timeout = 500
scan_timeout = 30

[line_break]
disabled = true

[character]
disabled = true

[palettes.gruvbox_dark]
aqua = "#689d6a"
bg1 = "#3c3836"
bg3 = "#665c54"
blue = "#458588"
fg0 = "#fbf1c7"
green = "#98971a"
orange = "#d65d0e"
purple = "#b16286"
red = "#cc241d"
yellow = "#d79921"

[palettes.tokyo_night]
aqua = "#689d6a"
black = "#15161e"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
orange = "#d65d0e"
purple = "#bb9af7"
red = "#f7768e"
white = "#a9b1d6"
yellow = "#e0af68"

[directory]
format = "[ $path]($style)"
style = "fg:yellow bold"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~/Git/gitlab.ptsecurity.com/ptcs" = "…/ptcs"

[git_branch]
format = "[ $symbol $branch]($style)"
style = "fg:aqua bold"
symbol = ""

[git_commit]
format = "[( $hash$tag)]($style)"
style = "fg:green bold"

[git_status]
format = "[( $all_status$ahead_behind)]($style)"
style = "fg:red bold"

[c]
format = "[ $symbol( $version)]($style)"
style = "fg:yellow"
symbol = " "

[cmd_duration]
format = "[  $duration]($style)"
style = "bold fg:orange"
min_time = 10_000
show_notifications = false
min_time_to_notify = 60_000

[golang]
format = "[ $symbol( $version)]($style)"
style = "fg:cyan"
symbol = ""

[helm]
format = "[ $symbol( $version)]($style)"
style = "fg:blue"
symbol = "⎈"

[kubernetes]
disabled = false
format = "[ $symbol $context( ($namespace))]($style)"
style = "fg:blue bold"
symbol = "⎈"

[python]
format = "[ $symbol( $version)]($style)"
style = "fg:green"
symbol = ""

[rust]
format = "[ $symbol( $version)]($style)"
style = "fg:orange"
symbol = ""

[lua]
format = "[ $symbol( $version)]($style)"
style = "fg:blue"
symbol = "󰢱"
